sonar.projectKey=ifs24051-pabwe2026-nextjs
sonar.projectName=ifs24051-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,src/server.ts,src/setupTests.ts,src/test-utils.tsx,src/types/**,src/**/*.d.ts,src/app/**/layout.tsx,src/app/layout.tsx,**/*.test.ts,**/*.test.tsx